export default{
    Get_An_Exclusively_Brewed_Digital_Solution_For_Your_Business:'Get An Exclusively Brewed Digital Solution For Your Business',
    New_User:'New User? ',
    Already_have_an_account:'Already have an account?',
    User_Details:'User Details',
    Name:'Name : ',
    Age:'Age : ',
    Email:'Email : ',
    Mobile:'Mobile : ',
    Please_enter_your_username:"Please enter your username",
    Please_enter_your_password:'Please enter your password',
    Submit:"SUBMIT",
    Back:"  Back  ",
    Login_With_Your_Details:'Login With Your Details',
    REGISTRATION_FORM:'REGISTRATION FORM',
    Already_have_an_account:'Already have an account ? ',
    Login:'Login',
    Enter_Your_Name:"Enter Your Name",
    Enter_Your_age:"Enter Your age",
    Enter_Your_Email:"Enter Your Email",
    Enter_Your_Mobile_Number:"Enter Your Mobile Number",
}